# Generated by Django 5.0.3 on 2024-04-15 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='rooms_joined', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'rooms',
                'db_table': 'room',
            },
        ),
    ]
