# Generated by Django 5.0.3 on 2024-04-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='rooms'),
        ),
    ]
