# Generated by Django 5.0.3 on 2024-05-31 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
    ]
